runtime: java
env: flex
instance_class: F4
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "21"
handlers:
  - url: .*
    script: auto
automatic_scaling:
  min_num_instances: 2
  max_num_instances: 5
service_account: tokyo-portal-454122-e0@appspot.gserviceaccount.com