openapi: 3.0.3
info:
  title: Address specification
  description: Address specification
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /api/address:
    get:
      description: |
        Endpoint used for getting paged addresses
      tags:
        - "Address"
      operationId: getAddresses
      parameters:
        - name: page
          in: query
          required: false
          allowEmptyValue: true
          schema:
            type: integer
        - name: size
          in: query
          required: false
          allowEmptyValue: true
          schema:
            type: integer
      responses:
        "200":
          description: Ok. Successful response will return ok status and list of all addresses
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PagedAddresses"
    post:
      description: |
        Endpoint used for adding new addresses
      tags:
        - "Address"
      operationId: addAddress
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Address"
      responses:
        "200":
          description: Ok. Successful response after adding new address will return ok status and id of added address
          content:
            application/json:
              schema:
                type: integer
                format: int64
                nullable: true
  /api/address/{id}:
    get:
      description: |
        Endpoint used for getting specified address object
      tags:
        - "Address"
      operationId: getAddress
      parameters:
        - name: id
          in: path
          required: true
          allowEmptyValue: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Ok. Successful response will return ok status with address object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Address"
    patch:
      description: |
        Endpoint used for updating address objects
      tags:
        - "Address"
      operationId: updateAddress
      parameters:
        - name: id
          in: path
          required: true
          allowEmptyValue: false
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Address"
      responses:
        "200":
          description: Ok. Successful response will return ok status after updating address
    delete:
      description: |
        Endpoint used for deleting address
      tags:
        - "Address"
      operationId: deleteAddress
      parameters:
        - name: id
          in: path
          required: true
          allowEmptyValue: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Ok. Successful response will return ok status
components:
  schemas:
    PagedAddresses:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/Address"
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64
    Address:
      type: object
      properties:
        id:
          type: integer
          format: int64
        street:
          type: string
          maxLength: 150
        postalCode:
          type: string
        city:
          type: string
          maxLength: 100
        country:
          type: string
          maxLength: 100
        latitude:
          type: number
        longitude:
          type: number