openapi: 3.0.3
info:
  title: Dance specification
  description: Dance specification
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /api/dances:
    put:
      description: |
        Endpoint used for adding new or updating existing dance
      tags:
        - "Dance"
      operationId: setDance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DanceRequest"
      responses:
        "200":
          description: Ok. Successful response will return ok status and updated element
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Dance"
    get:
      description: |
        Endpoint used for getting list of all dances
      tags:
        - "Dance"
      operationId: getDances
      parameters:
        - name: locale
          in: query
          required: false
          allowEmptyValue: true
          schema:
            type: string
        - name: phrase
          in: query
          required: false
          allowEmptyValue: true
          schema:
            type: string
      responses:
        "200":
          description: Ok. Successful response will return ok status and list of dances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Dance"
  /api/dances/{id}:
    description: |
      Endpoint for getting dance by id
    get:
      tags:
        - "Dance"
      operationId: getDanceById
      parameters:
        - name: id
          in: path
          required: true
          allowEmptyValue: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Ok. Successful response will return ok status and specified dance
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DanceRequest"
    delete:
      description: |
        Endpoint used for deleting dance by id
      tags:
        - "Dance"
      operationId: deleteDance
      parameters:
        - name: id
          in: path
          required: true
          allowEmptyValue: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Ok. Successful response will return ok status
components:
  schemas:
    Dance:
      type: object
      properties:
        id:
          type: integer
          format: int64
        locale:
          type: string
        name:
          type: string
    PagedDances:
      type: object
      properties:
        totalElements:
          type: integer
        totalPages:
          type: integer
        content:
          type: array
          items:
            $ref: "#/components/schemas/Dance"
    DanceRequest:
      type: object
      properties:
        id:
          type: integer
          format: int64
        locale:
          type: string
        name:
          type: string
        translations:
          type: array
          items:
            $ref: "#/components/schemas/DanceTranslation"
    DanceTranslation:
      type: object
      properties:
        id:
          type: integer
          format: int64
        locale:
          type: string
        value:
          type: string
