openapi: 3.0.3
info:
  title: Dance specification
  description: Dance specification
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  
components:
  schemas:
    Dance:
      type: object
      properties:
        id:
          type: integer
          format: int64
        locale:
          type: string
        name:
          type: string
