openapi: 3.0.3
info:
  title: Files specification
  description: Files specification
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /api/files/upload-files:
    description: |
      Endpoint used for uploading files
    post:
      tags:
        - "Files"
      operationId: uploadFiles
      parameters:
        - name: teamId
          in: query
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        "200":
          description: Ok. Successful response will return ok status after file upload
  /api/files/get-files-list:
    description: |
      Endpoint used for getting list of files (admin), for specific will use different endpoints
    get:
      tags:
        - "Files"
      operationId: getFilesList
      responses:
        "200":
          description: Ok. Successful response will return ok status and list of files.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /api/files/get-team-files:
    description: |
      Endpoint used for getting dancing team files list
    get:
      tags:
        - "Files"
      operationId: getTeamFiles
      parameters:
        - name: teamId
          in: query
          required: true
          allowEmptyValue: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Ok. Successful response will return ok status and list of team files
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /api/files/get-file:
    description: |
      Endpoint used for getting requested file
    get:
      tags:
        - "Files"
      operationId: getFile
      parameters:
        - name: filename
          in: query
          required: true
          allowEmptyValue: false
          schema:
            type: string
      responses:
        "200":
          description: Ok. Successful response will return ok status and file
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
  /api/files/get-gallery-urls:
    description: |
      Endpoint used for getting list of 10 last images names to gallery
    get:
      tags:
        - "Files"
      operationId: getGalleryUrls
      parameters:
        - name: teamId
          in: query
          required: true
          allowEmptyValue: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Ok. Successful response will return list of image names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
