openapi: 3.0.3
info:
  title: Files specification
  description: Files specification
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /api/files/{teamId}/{fileType}:
    description: |
      Endpoint used to sending new images on server,
      or getting existing images
    get:
      tags:
        - "Files"
      operationId: getImage
      parameters:
        - name: teamId
          in: path
          required: true
          allowEmptyValue: false
          schema:
            type: integer
            format: int64
        - name: fileType
          in: path
          required: true
          allowEmptyValue: false
          schema:
            type: string
        - name: filename
          in: query
          required: false
          allowEmptyValue: true
          schema:
            type: string
            nullable: true
      responses:
        "200":
          description: Ok. Successful response will return specified file
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
    post:
      tags:
        - "Files"
      operationId: saveNewImage
      parameters:
        - name: teamId
          in: path
          required: true
          allowEmptyValue: false
          schema:
            type: integer
            format: int64
        - name: fileType
          in: path
          required: true
          allowEmptyValue: false
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "200":
          description: Ok. Image has been successfully saved
    put:
      tags:
        - "Files"
      operationId: updateImage
      parameters:
        - name: teamId
          in: path
          required: true
          allowEmptyValue: false
          schema:
            type: integer
            format: int64
        - name: fileType
          in: path
          required: true
          allowEmptyValue: false
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "200":
          description: Ok. Image has been successfully changed
  /api/files/{teamId}:
    delete:
      tags:
        - "Files"
      operationId: deleteImage
      parameters:
        - name: teamId
          in: path
          required: true
          allowEmptyValue: false
          schema:
            type: integer
            format: int64
        - name: filename
          in: query
          required: false
          allowEmptyValue: true
          schema:
            type: string
            nullable: true
      responses:
        "200":
          description: Ok. Image has been successfully deleted
