openapi: 3.0.3
info:
  title: Hello specification
  description: Hello test specification
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /hello/{name}:
    description: |
      Endpoint for getting greetings
    get:
      tags:
        - "Hello"
      operationId: HelloWithGreetings
      parameters:
        - name: name
          in: path
          required: false
          allowEmptyValue: false
          schema:
            type: string
      responses:
        "200":
          description: |
            Ok. Successful request returns greetings
          content:
            application/text:
              schema:
                type: string

