openapi: 3.0.3
info:
  title: Messaging specification
  description: Admin only specification with endpoint used for sending notifications
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /fcm/send-message:
    description: |
      Endpoint used for sending data to specific users
    post:
      tags:
        - "CloudMessages"
      operationId: sendMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MessageRequest"
      responses:
        "200":
          description: Ok. Successful response will return ok status an list of responses
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /fcm/add-device-token:
    description: |
      Endpoint used for adding device token for push notifications
    post:
      tags:
        - "CloudMessages"
      operationId: addDeviceToken
      parameters:
        - name: token
          in: query
          required: true
          allowEmptyValue: false
          schema:
            type: string
        - name: deviceType
          in: query
          required: true
          allowEmptyValue: false
          schema:
            type: string
      responses:
        "200":
          description: Ok. Successful response will return ok status
  /fcm/delete-device-token:
    description: Endpoint used for deleting token from tokens list
    post:
      tags:
        - "CloudMessages"
      operationId: deleteDeviceToken
      parameters:
        - name: tokenId
          in: query
          required: true
          allowEmptyValue: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Ok. Successful response will return ok status
  /fcm/add-subscription:
    description: |
      Endpoint used for subscribing dancing teams
    post:
      tags:
        - "CloudMessages"
      operationId: addSubscription
      parameters:
        - name: dancingTeamId
          in: query
          required: true
          allowEmptyValue: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Ok. Successful response will return ok status
  /fcm/delete-subscription:
    description: |
      Endpoint used for deleting subscription
    post:
      tags:
        - "CloudMessages"
      operationId: deleteSubscription
      parameters:
        - name: subscriptionId
          in: query
          required: true
          allowEmptyValue: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Ok. Successful response will return ok status
components:
  schemas:
    MessageRequest:
      type: object
      properties:
        receivers:
          type: array
          items:
            type: string
        title:
          type: string
        message:
          type: string
        additionalData:
          type: object
          additionalProperties:
            type: string