openapi: 3.0.3
info:
  title: Region Specification
  description: Region Specification
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /api/regions:
    description: |
      Endpoint used for adding, updating, deleting and getting regions
    get:
      tags:
        - "Region"
      operationId: getRegions
      parameters:
        - name: name
          in: query
          required: false
          allowEmptyValue: true
          schema:
            type: string
      responses:
        "200":
          description: Ok. Successful response will return list of regions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Region"
    post:
      tags:
        - "Region"
      operationId: addRegion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Region"
      responses:
        "200":
          description: Ok. Successful response will return ok status and created object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Region"
    patch:
      tags:
        - "Region"
      operationId: updateRegion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Region"
      responses:
        "200":
          description: Ok. Successful response will return ok status and updated object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Region"
  /api/regions/{id}:
    description: |
      Endpoint used for getting region by id
    get:
      tags:
        - "Region"
      operationId: getRegionById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: withTranslations
          in: query
          required: false
          allowEmptyValue: true
          schema:
            type: boolean
      responses:
        "200":
          description: Ok. Successful response will return ok status and specified region object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Region"
    delete:
      tags:
        - "Region"
      operationId: deleteRegion
      parameters:
        - name: id
          in: path
          required: true
          allowEmptyValue: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Ok. Successful response will return ok status
  /api/regions/translations/{id}:
    description: |
      Endpoint used for getting region translations
    get:
      tags:
        - "Region"
      operationId: getRegionTranslations
      parameters:
        - name: regionId
          in: path
          required: true
          allowEmptyValue: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Ok. Successfully get list of specified region translations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Translation"
  /api/regions/get-by-locale:
    description: |
      Endpoint used for getting list of regions by locale
    get:
      tags:
        - "Region"
      operationId: getByLocale
      parameters:
        - name: locale
          in: query
          required: true
          allowEmptyValue: false
          schema:
            type: string
      responses:
        "200":
          description: Ok. Successful response will return ok status and list of regions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Region"
components:
  schemas:
    Region:
      type: object
      properties:
        id:
          type: integer
          format: int64
        locale:
          type: string
        name:
          type: string
        translations:
          type: array
          nullable: true
          items:
            $ref: "#/components/schemas/Translation"
    Translation:
      type: object
      properties:
        locale:
          type: string
        specifier:
          type: string
        value:
          type: string

