openapi: 3.0.3
info:
  title: Region Specification
  description: Region Specification
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:

components:
  schemas:
    Region:
      type: object
      properties:
        id:
          type: integer
          format: int64
        locale:
          type: string
        name:
          type: string
