openapi: 3.0.3
info:
  title: User specification
  description: Specification with user management operations and roles (only for admin)
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /users/add-user:
    description: |
      Endpoint for adding new users
    post:
      tags:
        - "User"
      operationId: addUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: Ok. Successful response will return created user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /users/edit-user:
    description: |
      Endpoint for editing existing user
    patch:
      tags:
        - "User"
      operationId: editUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: Ok. Successful response will return edited user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /users/delete-user:
    description: |
      Endpoint for deleting user
    delete:
      tags:
        - "User"
      operationId: deleteUser
      parameters:
        - name: id
          in: query
          required: true
          allowEmptyValue: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Ok. User successfully deleted.
  /users/get-user-by-id:
    description: |
      Endpoint for getting user by id
    post:
      tags:
        - "User"
      operationId: getUserById
      parameters:
        - name: id
          in: query
          required: true
          allowEmptyValue: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Ok. Successful response will return requested user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /users/get-user-subscriptions:
    description: |
      Endpoint used for getting user subscriptions
    get:
      tags:
        - "User"
      operationId: getUserSubscriptions
      responses:
        "200":
          description: Ok. Successful response will return ok status and list of subscribed dancing teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "dancing-team-specification.yaml#/components/schemas/DancingTeamListElement"
  /users/register-user:
    description: |
      Endpoint used for registering normal user
    post:
      tags:
        - "User"
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterUserRequest"
      responses:
        "200":
          description: Ok. Successful response will return ok status
  /users/register-as-dancing-team:
    description: |
      Endpoint used for registering dancing team account
    post:
      tags:
        - "User"
      operationId: registerAsDancingTeam
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterDancingTeamAccountRequest"
      responses:
        "200":
          description: Ok. Successful response will return ok status
  /users/login:
    description: |
      Endpoint used for logging-in users
    post:
      tags:
        - "User"
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Ok. Successful response will return ok status and tokens in response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
  /users/refresh-token:
    description: |
      Endpoint used for refreshing token
    post:
      tags:
        - "User"
      operationId: refreshToken
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshTokenRequest"
      responses:
        "200":
          description: Ok. Successful response will return ok status and refreshed token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RefreshTokenResponse"
  /users/add-device-token:
    description: |
      Endpoint used for assigning device token to account
    post:
      tags:
        - "User"
      operationId: addDeviceToken
      parameters:
        - name: token
          in: query
          required: true
          allowEmptyValue: false
          schema:
            type: string
        - name: deviceType
          in: query
          required: true
          allowEmptyValue: false
          schema:
            type: string
      responses:
        "200":
          description: Ok. Successful response will return ok status and token has saved
        "201":
          description: Ok. Successful response will return ok status and token is already in database
components:
  schemas:
    RegisterUserRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        firstName:
          type: string
        lastName:
          type: string
    RegisterDancingTeamAccountRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        teamName:
          type: string
        teamDescription:
          type: string
        creationYear:
          type: integer
        regionId:
          type: integer
          format: int64
        city:
          type: string
        street:
          type: string
        houseNumber:
          type: string
    UserData:
      type: object
      properties:
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        userType:
          type: string
        userRoles:
          type: array
          items:
            $ref: "#/components/schemas/UserRole"
    UserRole:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        dancingTeamId:
          type: integer
          format: int64
          nullable: true
    DancingTeamData:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        teamName:
          type: string
        teamDescription:
          type: string
        creationYear:
          type: integer
        regionId:
          type: integer
          format: int64
        city:
          type: string
        street:
          type: string
        houseNumber:
          type: string
    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    LoginResponse:
      type: object
      properties:
        idToken:
          type: string
        refreshToken:
          type: string
        userData:
          $ref: "#/components/schemas/UserData"
        dancingTeamData:
          $ref: "#/components/schemas/DancingTeamData"
    RefreshTokenRequest:
      type: object
      properties:
        refreshToken:
          type: string
    RefreshTokenResponse:
      type: object
      properties:
        token:
          type: string
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        brithDate:
          type: string
          format: date
        howLongDancing:
          type: integer
        dances:
          type: array
          items:
            $ref: "dance-specification.yaml#/components/schemas/Dance"
        howLongPlayingInstruments:
          type: integer
        instruments:
          type: array
          items:
            $ref: "music-instrument-specification.yaml#/components/schemas/MusicInstrument"
        #        role:
        #          $ref: "#/components/schemas/Role"
        userType:
          type: string
    Role:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string

  
